#? Config file for btop v.1.4.6
# Stripped to active config only — full docs: https://github.com/aristocratos/btop

# theme
color_theme = "/opt/homebrew/Cellar/btop/1.4.4/share/btop/themes/everforest-dark-hard.theme"
theme_background = true
truecolor = true
force_tty = true
rounded_corners = true
terminal_sync = true

# layout
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
shown_boxes = "proc cpu mem"
clock_format = "%X"

# input
vim_keys = true

# graphs
graph_symbol = "braille"
graph_symbol_cpu = "default"
graph_symbol_mem = "block"
graph_symbol_net = "default"
graph_symbol_proc = "braille"
update_ms = 2000

# cpu
cpu_graph_upper = "Auto"
cpu_graph_lower = "Auto"
cpu_invert_lower = true
cpu_single_graph = false
cpu_bottom = false
show_uptime = true
show_cpu_watts = true
show_cpu_freq = true
check_temp = true
cpu_sensor = "Auto"
show_coretemp = true
cpu_core_map = ""
temp_scale = "celsius"

# processes
proc_sorting = "cpu lazy"
proc_reversed = false
proc_tree = true
proc_colors = true
proc_gradient = true
proc_per_core = false
proc_mem_bytes = true
proc_cpu_graphs = true
proc_info_smaps = false
proc_left = false
proc_filter_kernel = false
proc_aggregate = false
keep_dead_proc_usage = false

# memory
mem_graphs = true
mem_below_net = false
zfs_arc_cached = true
show_swap = false
swap_disk = true
show_disks = false
only_physical = true
use_fstab = true
zfs_hide_datasets = false
disk_free_priv = false
show_io_stat = false
io_mode = false
io_graph_combined = true
io_graph_speeds = ""
base_10_sizes = false

# network
net_download = 100
net_upload = 100
net_auto = true
net_sync = true
net_iface = ""
base_10_bitrate = "Auto"

# battery
show_battery = true
selected_battery = "Auto"
show_battery_watts = true

# system
background_update = true
custom_cpu_name = ""
disks_filter = ""
log_level = "WARNING"
save_config_on_exit = true
