#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# amazon aws/ec2/as settings
export EC2_HOME=$HOME/Documents/bin/ec2
export AWS_AUTO_SCALING_HOME=$HOME/Documents/bin/as
export AWS_ACCESS_KEY=AKIAIGWLPVJVNJQV2YZQ
export AWS_SECRET_KEY=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
export AWS_CREDENTIAL_FILE=$HOME/Documents/products/aws/credentials.cnf

# also, look for my personal binaries
export PATH=$HOME/bin:$EC2_HOME/bin:$AWS_AUTO_SCALING_HOME/bin:$HOME/Library/Python/2.7/bin:$PATH

export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

export VISUAL="mvim -v"
export EDITOR="mvim -v"
