#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# find mvim
export PATH=$PATH:/opt/mvim

# find powerline
export PATH=$PATH:$HOME/Library/Python/2.7/bin

# set up autoscaling tools
export AWS_AUTO_SCALING_HOME=/opt/as
export PATH=$PATH:$AWS_AUTO_SCALING_HOME/bin
source ./aws_creds

# set the java home dir
export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

# use ansible from the dev git checkout
export PATH=$PATH:/opt/ansible/bin
cd /opt/ansible && source /opt/ansible/hacking/env-setup >> /dev/null && cd -

# use macvim with shell utilities
export VISUAL="mvim -v"
export EDITOR="mvim -v"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
