[general]
# live_config_reload = true

import = ["~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"]

[window]
# decorations = "buttonless"
decorations = "transparent"
dimensions = { columns = 94, lines = 200 }
dynamic_padding = false
# padding = { x = 25, y = 56 }
padding = { x = 10, y = 64 }
opacity = 0.7
blur = true
dynamic_title = true
option_as_alt = "both"

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
size = 18

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"

[cursor]
style = { shape = "beam", blinking = "always" }
vi_mode_style = { shape = "block", blinking = "always" }

[keyboard]
bindings = [
    { key = "V", mods = "Command|Shift", mode = "~Search", action = "ToggleViMode" },
]
