if [ -f ~/.bash_login ]; then
  . ~/.bash_login
fi

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# enable programmable completion features
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

# powerline
# comment this out if powerline is not installed
# (otherwise, the shell prompt will break)
function _update_ps1() {
    PS1="$(~/powerline-shell.py --mode flat $? 2> /dev/null)"
}
if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
