# avoid mistakes
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
# FIXME
# http://hintsforums.macworld.com/archive/index.php/t-9123.html
# alias rm='mv \!* ~/.Trash/'

# tweaks
alias ll='ls -lah'
alias lt='ls -lhrt'
#alias pu='pushd $* > /dev/null'
#alias po='popd > /dev/null'

# neovim instead of vim
alias vim=/usr/local/bin/nvim

# vim instead of less
alias less=/usr/local/bin/vimpager

# usage
alias usage='du -ak|sort -nr|less'
#alias hog='du -ks * | sort -nr | pg'
#alias hog='du -khs * | sort -nr'
#alias hog='du -m * | sort -nr'
#alias hogs='du -ms * | sort -nr'
alias hog='du -gs * | sort -nr'
# FIXME (argument)
alias dutotal='du -ch $1 | tail -1'

# tools
#alias myip='curl -s https://secure.internode.on.net/webtools/showmyip\?textonly=1'
#alias myip='curl http://ifcfg.net'
alias myip='curl http://wtfismyip.com/text'
# FIXME argument
alias isreg='whois $1 | grep -q "No match" && echo "No" || echo "Yes"'

# fpg
alias hda='cd /Users/mo/Google\ Drive/projects/hda'
alias uc='cd /Users/mo/Google\ Drive/projects/uc'
