# source .bashrc
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# use vim instead of less
export PAGER=/usr/local/bin/vimpager

# use brew binaries first
export PATH=/usr/local/bin:$PATH

# java
export JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/'

# go
export GOPATH=$HOME/Documents/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# increase the number of commands remembered in the history
export HISTSIZE=901

# colorise ls
if [ -f ~/.dir_colors ]; then
  export LSCOLORS="gxfxcxdxbxegedabagacad"
fi
