# process .bashrc
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# vim instead of less
export PAGER=/usr/local/bin/vimpager

# macvim instead of vim
export EDITOR='mvim -v'
export VISUAL='mvim -v'

# java
export JAVA_HOME='/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/'
